source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Eulalia' do
    pod 'Alamofire', '~> 3.4'
    pod 'GoogleMaps'
end

#target :<#TargetName#>Tests, :exclusive => true do
  # pod 'Kiwi'
#end
